### ISSUE TITLE
Look for symbols to use

### ISSUE THREAD

**Issue by aslinedvinsson** [aslinedvinsson/Axisofaccesshack#13]

**Comment by AshLaw96** [comment]
**Home-page-icon**
https://icones.js.org/collection/dashicons?s=home&icon=dashicons:admin-home
**Search-icon**
https://icones.js.org/collection/dashicons?s=search&icon=dashicons:search
**chat-icon**
https://icones.js.org/collection/dashicons?s=form&icon=dashicons:format-chat
so that if user wants to talk to career or vice versa they can do so on the app.
**call-for-help-icon**
https://icones.js.org/collection/healthicons?s=help&icon=healthicons:contact-support
**medication-icon**
https://icones.js.org/collection/healthicons?category=Medications&icon=healthicons:medicines
career can click icon and informs the user they need to take pills/meds
**contact-page-icon**
https://icones.js.org/collection/material-symbols?s=envelope&icon=material-symbols:stacked-email-outline
**add-more-icon**
https://icones.js.org/collection/material-symbols?s=add-c&icon=material-symbols:add-circle
so user or career can add more main icons.
**calendar-icon**
https://icones.js.org/collection/healthicons?s=calend&icon=healthicons:calendar
So user can add appointments or career can send reminders to user of appointments.
**Emergency-icon**
https://icones.js.org/collection/healthicons?s=emergency&icon=healthicons:accident-and-emergency

**Comment by AshLaw96** [comment]
**medical-records-icon**
https://icones.js.org/collection/healthicons?s=medical&icon=healthicons:medical-records-negative
**health-faq-icon**
https://icones.js.org/collection/healthicons?s=question&icon=healthicons:question-triangle
frequently asked medical questions.
**accessibility-icons**
https://icones.js.org/collection/healthicons?category=Conditions&icon=healthicons:deaf
https://icones.js.org/collection/healthicons?category=Conditions&icon=healthicons:low-vision
Depending on the users disability could make the images bigger if they have low-vision or turn screen-reader on if no vision.
**social-media-icons**
Facebook
https://icones.js.org/collection/entypo-social?s=fa&icon=entypo-social:facebook
Instagram
https://icones.js.org/collection/entypo-social?s=ins&icon=entypo-social:instagram
Twitter
https://icones.js.org/collection/entypo-social?s=twitt&icon=entypo-social:twitter
LinkedIn
https://icones.js.org/collection/entypo-social?s=lin&icon=entypo-social:linkedin

**Comment by BadrAlioui** [comment]
[toilet](https://openmoji.org/library/emoji-1F6BD/)
